# Loading Dependencies

In [1]:
import pandas as pd
import numpy as np

# Data Loading

In [2]:
df = pd.read_csv('data.csv')
df.head()

          Brand Category  Color Size Material  Price
0   New Balance    Dress  White   XS    Nylon    182
1   New Balance    Jeans  Black   XS     Silk     57
2  Under Armour    Dress    Red    M     Wool    127
3          Nike    Shoes  Green    M   Cotton     77
4        Adidas  Sweater  White    M    Nylon    113

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 6 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Brand     1000 non-null   object
 1   Category  1000 non-null   object
 2   Color     1000 non-null   object
 3   Size      1000 non-null   object
 4   Material  1000 non-null   object
 5   Price     1000 non-null   int64
dtypes: int64(1), object(5)
memory usage: 47.0+ KB

In [4]:
correlation_matrix = df.corr()
print(correlation_matrix)

       Price
Price    1.0

<ipython-input-4-becb50483c66>:1: FutureWarning: The default value of numeric_only in DataFrame.corr is deprecated. In a future version, it will default to False. Select only valid columns or specify the value of numeric_only to silence this warning.
  correlation_matrix = df.corr()

In [5]:
df.head()

          Brand Category  Color Size Material  Price
0   New Balance    Dress  White   XS    Nylon    182
1   New Balance    Jeans  Black   XS     Silk     57
2  Under Armour    Dress    Red    M     Wool    127
3          Nike    Shoes  Green    M   Cotton     77
4        Adidas  Sweater  White    M    Nylon    113

# Data Cleaning

In [6]:
df.isnull().sum()

Brand       0
Category    0
Color       0
Size        0
Material    0
Price       0
dtype: int64

In [7]:
drop_df = df.dropna()

In [8]:
drop_df.isnull().sum()

Brand       0
Category    0
Color       0
Size        0
Material    0
Price       0
dtype: int64

In [9]:
drop_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 6 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Brand     1000 non-null   object
 1   Category  1000 non-null   object
 2   Color     1000 non-null   object
 3   Size      1000 non-null   object
 4   Material  1000 non-null   object
 5   Price     1000 non-null   int64
dtypes: int64(1), object(5)
memory usage: 47.0+ KB

In [10]:
no_duplicates = drop_df.drop_duplicates()

In [11]:
no_duplicates.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 1000 entries, 0 to 999
Data columns (total 6 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Brand     1000 non-null   object
 1   Category  1000 non-null   object
 2   Color     1000 non-null   object
 3   Size      1000 non-null   object
 4   Material  1000 non-null   object
 5   Price     1000 non-null   int64
dtypes: int64(1), object(5)
memory usage: 54.7+ KB

# One Hot Categorical Endcoding

In [12]:
df['Category'].unique()

array(['Dress', 'Jeans', 'Shoes', 'Sweater', 'Jacket', 'T-shirt'],
      dtype=object)

In [13]:
df = pd.get_dummies(df, columns=['Category'], prefix='Category', dtype='int64')

In [14]:
df['Color'].unique()

array(['White', 'Black', 'Red', 'Green', 'Yellow', 'Blue'], dtype=object)

In [15]:
df = pd.get_dummies(df, columns=['Color'], prefix='Color', dtype='int64')

In [16]:
df['Size'].unique()

array(['XS', 'M', 'XL', 'XXL', 'S', 'L'], dtype=object)

In [17]:
df = pd.get_dummies(df, columns=['Size'], prefix='Size', dtype='int64')

In [18]:
df['Material'].unique()

array(['Nylon', 'Silk', 'Wool', 'Cotton', 'Polyester', 'Denim'],
      dtype=object)

In [19]:
df = pd.get_dummies(df, columns=['Material'], prefix='Material', dtype='int64')

In [20]:
df['Brand'].unique()

array(['New Balance', 'Under Armour', 'Nike', 'Adidas', 'Reebok', 'Puma'],
      dtype=object)

In [21]:
df = pd.get_dummies(df, columns=['Brand'], prefix='Brand', dtype='int64')

In [22]:
df

,Price,Category_Dress,Category_Jacket,Category_Jeans,Category_Shoes,Category_Sweater,Category_T-shirt,Color_Black,Color_Blue,Color_Green,...,Material_Nylon,Material_Polyester,Material_Silk,Material_Wool,Brand_Adidas,Brand_New Balance,Brand_Nike,Brand_Puma,Brand_Reebok,Brand_Under Armour
0,182,1,0,0,0,0,0,0,0,0,...,1,0,0,0,0,1,0,0,0,0
1,57,0,0,1,0,0,0,1,0,0,...,0,0,1,0,0,1,0,0,0,0
2,127,1,0,0,0,0,0,0,0,0,...,0,0,0,1,0,0,0,0,0,1
3,77,0,0,0,1,0,0,0,0,1,...,0,0,0,0,0,0,1,0,0,0
4,113,0,0,0,0,1,0,0,0,0,...,1,0,0,0,1,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,176,0,0,1,0,0,0,1,0,0,...,0,1,0,0,0,0,0,1,0,0
996,110,0,1,0,0,0,0,0,0,0,...,0,0,1,0,0,0,0,1,0,0
997,127,0,0,0,0,1,0,0,1,0,...,0,0,0,0,0,0,0,0,1,0
998,69,0,0,0,0,1,0,1,0,0,...,0,0,0,0,0,0,0,0,0,1
999,174,0,1,0,0,0,0,0,0,0,...,0,0,0,1,0,1,0,0,0,0

# Min Max Scaling

In [23]:
df.describe()

,Price,Category_Dress,Category_Jacket,Category_Jeans,Category_Shoes,Category_Sweater,Category_T-shirt,Color_Black,Color_Blue,Color_Green,...,Material_Nylon,Material_Polyester,Material_Silk,Material_Wool,Brand_Adidas,Brand_New Balance,Brand_Nike,Brand_Puma,Brand_Reebok,Brand_Under Armour
count,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1000.00000,1000.00000,1000.000000,...,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000
mean,106.289000,0.166000,0.191000,0.167000,0.172000,0.160000,0.144000,0.16300,0.16300,0.162000,...,0.155000,0.175000,0.173000,0.172000,0.166000,0.164000,0.165000,0.168000,0.158000,0.179000
std,53.695444,0.372267,0.393286,0.373162,0.377569,0.366789,0.351265,0.36955,0.36955,0.368635,...,0.362086,0.380157,0.378437,0.377569,0.372267,0.370461,0.371366,0.374053,0.364924,0.383544
min,10.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.00000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,59.750000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.00000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
50%,108.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.00000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
75%,150.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.00000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
max,199.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.00000,1.00000,1.000000,...,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000

In [24]:
from sklearn.preprocessing import MinMaxScaler

In [25]:
scaler = MinMaxScaler()

In [26]:
standardized_data = scaler.fit_transform(df)

In [27]:
standardized_df = pd.DataFrame(standardized_data, columns=df.columns)

In [28]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 31 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Price               1000 non-null   int64
 1   Category_Dress      1000 non-null   int64
 2   Category_Jacket     1000 non-null   int64
 3   Category_Jeans      1000 non-null   int64
 4   Category_Shoes      1000 non-null   int64
 5   Category_Sweater    1000 non-null   int64
 6   Category_T-shirt    1000 non-null   int64
 7   Color_Black         1000 non-null   int64
 8   Color_Blue          1000 non-null   int64
 9   Color_Green         1000 non-null   int64
 10  Color_Red           1000 non-null   int64
 11  Color_White         1000 non-null   int64
 12  Color_Yellow        1000 non-null   int64
 13  Size_L              1000 non-null   int64
 14  Size_M              1000 non-null   int64
 15  Size_S              1000 non-null   int64
 16  Size_XL             1000 non-null   int64
 17  Size_XS             1000 non-null   int64
 18  Size_XXL            1000 non-null   int64
 19  Material_Cotton     1000 non-null   int64
 20  Material_Denim      1000 non-null   int64
 21  Material_Nylon      1000 non-null   int64
 22  Material_Polyester  1000 non-null   int64
 23  Material_Silk       1000 non-null   int64
 24  Material_Wool       1000 non-null   int64
 25  Brand_Adidas        1000 non-null   int64
 26  Brand_New Balance   1000 non-null   int64
 27  Brand_Nike          1000 non-null   int64
 28  Brand_Puma          1000 non-null   int64
 29  Brand_Reebok        1000 non-null   int64
 30  Brand_Under Armour  1000 non-null   int64
dtypes: int64(31)
memory usage: 242.3 KB

In [29]:
df.head()

,Price,Category_Dress,Category_Jacket,Category_Jeans,Category_Shoes,Category_Sweater,Category_T-shirt,Color_Black,Color_Blue,Color_Green,...,Material_Nylon,Material_Polyester,Material_Silk,Material_Wool,Brand_Adidas,Brand_New Balance,Brand_Nike,Brand_Puma,Brand_Reebok,Brand_Under Armour
0,182,1,0,0,0,0,0,0,0,0,...,1,0,0,0,0,1,0,0,0,0
1,57,0,0,1,0,0,0,1,0,0,...,0,0,1,0,0,1,0,0,0,0
2,127,1,0,0,0,0,0,0,0,0,...,0,0,0,1,0,0,0,0,0,1
3,77,0,0,0,1,0,0,0,0,1,...,0,0,0,0,0,0,1,0,0,0
4,113,0,0,0,0,1,0,0,0,0,...,1,0,0,0,1,0,0,0,0,0

In [30]:
standardized_df.head()

,Price,Category_Dress,Category_Jacket,Category_Jeans,Category_Shoes,Category_Sweater,Category_T-shirt,Color_Black,Color_Blue,Color_Green,...,Material_Nylon,Material_Polyester,Material_Silk,Material_Wool,Brand_Adidas,Brand_New Balance,Brand_Nike,Brand_Puma,Brand_Reebok,Brand_Under Armour
0,0.910053,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
1,0.248677,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,...,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
2,0.619048,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0
3,0.354497,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
4,0.544974,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,...,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0

In [31]:
standardized_df.describe()

,Price,Category_Dress,Category_Jacket,Category_Jeans,Category_Shoes,Category_Sweater,Category_T-shirt,Color_Black,Color_Blue,Color_Green,...,Material_Nylon,Material_Polyester,Material_Silk,Material_Wool,Brand_Adidas,Brand_New Balance,Brand_Nike,Brand_Puma,Brand_Reebok,Brand_Under Armour
count,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1000.00000,1000.00000,1000.000000,...,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000
mean,0.509466,0.166000,0.191000,0.167000,0.172000,0.160000,0.144000,0.16300,0.16300,0.162000,...,0.155000,0.175000,0.173000,0.172000,0.166000,0.164000,0.165000,0.168000,0.158000,0.179000
std,0.284103,0.372267,0.393286,0.373162,0.377569,0.366789,0.351265,0.36955,0.36955,0.368635,...,0.362086,0.380157,0.378437,0.377569,0.372267,0.370461,0.371366,0.374053,0.364924,0.383544
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.00000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,0.263228,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.00000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
50%,0.518519,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.00000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
75%,0.740741,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.00000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
max,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.00000,1.00000,1.000000,...,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000